foreach(required
    TILEXR_MOONEP_KERNEL_BINARY
    TILEXR_MOONEP_KERNEL_EMBED_CPP
    TILEXR_MOONEP_KERNEL_DATA_SYMBOL
    TILEXR_MOONEP_KERNEL_SIZE_SYMBOL)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "${required} is required")
    endif()
endforeach()

if(NOT EXISTS "${TILEXR_MOONEP_KERNEL_BINARY}")
    message(FATAL_ERROR "MoonEP AICore binary not found: ${TILEXR_MOONEP_KERNEL_BINARY}")
endif()
if(NOT TILEXR_MOONEP_KERNEL_DATA_SYMBOL MATCHES "^[A-Za-z_][A-Za-z0-9_]*$" OR
   NOT TILEXR_MOONEP_KERNEL_SIZE_SYMBOL MATCHES "^[A-Za-z_][A-Za-z0-9_]*$")
    message(FATAL_ERROR "MoonEP embedded binary symbols must be C identifiers")
endif()

file(SIZE "${TILEXR_MOONEP_KERNEL_BINARY}" binarySize)
file(WRITE "${TILEXR_MOONEP_KERNEL_EMBED_CPP}" "/* Generated by embed_moonep_kernel.cmake. */
#include <cstddef>

extern \"C\" {
extern const std::size_t ${TILEXR_MOONEP_KERNEL_SIZE_SYMBOL} = ${binarySize};
}

asm(R\"(
.section .rodata, \"a\", @progbits
.balign 16
.global ${TILEXR_MOONEP_KERNEL_DATA_SYMBOL}
.type ${TILEXR_MOONEP_KERNEL_DATA_SYMBOL}, @object
${TILEXR_MOONEP_KERNEL_DATA_SYMBOL}:
.incbin \"${TILEXR_MOONEP_KERNEL_BINARY}\"
${TILEXR_MOONEP_KERNEL_DATA_SYMBOL}End:
.size ${TILEXR_MOONEP_KERNEL_DATA_SYMBOL}, ${TILEXR_MOONEP_KERNEL_DATA_SYMBOL}End - ${TILEXR_MOONEP_KERNEL_DATA_SYMBOL}
.previous
)\");
")
