if(NOT DEFINED TILEXR_MOONEP_PREFETCH_KERNEL_OP)
    message(FATAL_ERROR "TILEXR_MOONEP_PREFETCH_KERNEL_OP is required")
endif()
if(NOT DEFINED TILEXR_MOONEP_PREFETCH_KERNEL_EMBED_CPP)
    message(FATAL_ERROR "TILEXR_MOONEP_PREFETCH_KERNEL_EMBED_CPP is required")
endif()
if(NOT EXISTS "${TILEXR_MOONEP_PREFETCH_KERNEL_OP}")
    message(FATAL_ERROR
        "PrefetchWeight CCE object not found: ${TILEXR_MOONEP_PREFETCH_KERNEL_OP}")
endif()

file(SIZE "${TILEXR_MOONEP_PREFETCH_KERNEL_OP}" _tilexr_moonep_prefetch_kernel_size)

file(WRITE "${TILEXR_MOONEP_PREFETCH_KERNEL_EMBED_CPP}" "/*
 * Generated by src/moonep/cmake/embed_prefetch_weight_kernel.cmake.
 */
#include <cstddef>
#include <cstdint>

extern \"C\" {
extern const std::size_t TileXRMoonEpPrefetchWeightKernelBinarySize = ${_tilexr_moonep_prefetch_kernel_size};
}

asm(R\"(
.section .rodata, \"a\", @progbits
.balign 16
.global TileXRMoonEpPrefetchWeightKernelBinaryData
.type TileXRMoonEpPrefetchWeightKernelBinaryData, @object
TileXRMoonEpPrefetchWeightKernelBinaryData:
.incbin \"${TILEXR_MOONEP_PREFETCH_KERNEL_OP}\"
TileXRMoonEpPrefetchWeightKernelBinaryDataEnd:
.size TileXRMoonEpPrefetchWeightKernelBinaryData, TileXRMoonEpPrefetchWeightKernelBinaryDataEnd - TileXRMoonEpPrefetchWeightKernelBinaryData
.previous
)\");
")
