if(NOT DEFINED TILEXR_MOONEP_KERNEL_BINARY)
    message(FATAL_ERROR "TILEXR_MOONEP_KERNEL_BINARY is required")
endif()
if(NOT DEFINED TILEXR_MOONEP_KERNEL_EMBED_CPP)
    message(FATAL_ERROR "TILEXR_MOONEP_KERNEL_EMBED_CPP is required")
endif()
if(NOT DEFINED TILEXR_MOONEP_KERNEL_SYMBOL OR
   NOT TILEXR_MOONEP_KERNEL_SYMBOL MATCHES "^[A-Za-z_][A-Za-z0-9_]*$")
    message(FATAL_ERROR "TILEXR_MOONEP_KERNEL_SYMBOL must be a valid C identifier")
endif()
if(NOT EXISTS "${TILEXR_MOONEP_KERNEL_BINARY}")
    message(FATAL_ERROR "MoonEP AICore binary not found: ${TILEXR_MOONEP_KERNEL_BINARY}")
endif()

file(SIZE "${TILEXR_MOONEP_KERNEL_BINARY}" _tilexr_moonep_kernel_size)

file(WRITE "${TILEXR_MOONEP_KERNEL_EMBED_CPP}" "/*
 * Generated by src/moonep/cmake/embed_moonep_kernel.cmake.
 */
#include <cstddef>

extern \"C\" {
extern const std::size_t ${TILEXR_MOONEP_KERNEL_SYMBOL}Size = ${_tilexr_moonep_kernel_size};
}

asm(R\"(
.section .rodata, \"a\", @progbits
.balign 16
.global ${TILEXR_MOONEP_KERNEL_SYMBOL}Data
.type ${TILEXR_MOONEP_KERNEL_SYMBOL}Data, @object
${TILEXR_MOONEP_KERNEL_SYMBOL}Data:
.incbin \"${TILEXR_MOONEP_KERNEL_BINARY}\"
${TILEXR_MOONEP_KERNEL_SYMBOL}DataEnd:
.size ${TILEXR_MOONEP_KERNEL_SYMBOL}Data, ${TILEXR_MOONEP_KERNEL_SYMBOL}DataEnd - ${TILEXR_MOONEP_KERNEL_SYMBOL}Data
.previous
)\");
")
