#if defined(__DAV_C220_VEC__) || defined(__DAV_C310_VEC__)

#include "lccl_op.h"

LCCL_TYPE_AIV_FUNC(LCCL_ALLGATHER_FUNC_AUTO_DEF);
LCCL_TYPE_AIV_FUNC(LCCL_ALL_REDUCE_FUNC_AUTO_DEF);
LCCL_TYPE_AIV_FUNC(LCCL_REDUCE_SCATTER_FUNC_AUTO_DEF);
LCCL_TYPE_AIV_FUNC(LCCL_ALL2ALL_FUNC_AUTO_DEF);
LCCL_BROADCAST_FUNC_AUTO_DEF();
LCCL_PROFILE_PROBE_FUNC_AUTO_DEF();

#endif
