# Copyright (c) 2024-2026 TileXR Project
# Licensed under the Apache License, Version 2.0

if(NOT DEFINED TILEXR_GROUPED_ALLTOALL_KERNEL_OBJECT)
    message(FATAL_ERROR "TILEXR_GROUPED_ALLTOALL_KERNEL_OBJECT is required")
endif()
if(NOT DEFINED TILEXR_GROUPED_ALLTOALL_KERNEL_EMBED_CPP)
    message(FATAL_ERROR "TILEXR_GROUPED_ALLTOALL_KERNEL_EMBED_CPP is required")
endif()
if(NOT EXISTS "${TILEXR_GROUPED_ALLTOALL_KERNEL_OBJECT}")
    message(FATAL_ERROR
        "Grouped AllToAll CCE object not found: ${TILEXR_GROUPED_ALLTOALL_KERNEL_OBJECT}")
endif()

file(SIZE "${TILEXR_GROUPED_ALLTOALL_KERNEL_OBJECT}" _tilexr_grouped_kernel_size)
file(WRITE "${TILEXR_GROUPED_ALLTOALL_KERNEL_EMBED_CPP}" "/*
 * Generated by tests/udma/cmake/embed_grouped_alltoall_kernel.cmake.
 */
#include <cstddef>
#include <cstdint>

extern \"C\" {
extern const std::size_t TileXRGroupedAllToAllKernelBinarySize = ${_tilexr_grouped_kernel_size};
}

asm(R\"(
.section .rodata, \"a\", @progbits
.balign 16
.global TileXRGroupedAllToAllKernelBinaryData
.type TileXRGroupedAllToAllKernelBinaryData, @object
TileXRGroupedAllToAllKernelBinaryData:
.incbin \"${TILEXR_GROUPED_ALLTOALL_KERNEL_OBJECT}\"
TileXRGroupedAllToAllKernelBinaryDataEnd:
.size TileXRGroupedAllToAllKernelBinaryData, TileXRGroupedAllToAllKernelBinaryDataEnd - TileXRGroupedAllToAllKernelBinaryData
.previous
)\");
")
