/*
 * Copyright (c) 2026 TileXR Project
 *
 * Offline byte-level oracle for TileXR CCU lower-layer payloads.
 *
 * Reference hcomm files mirrored here as packed test-only structs:
 * - ccu_pfe/ccu_pfe_mgr.h
 * - ccu_pfe/ccu_pfe_mgr.cc
 * - ccu_jetty_ctx_mgr.h
 * - ccu_jetty_ctx_mgr.cc
 * - ccu_channel_ctx_v1/ccu_channel_ctx_mgr_v1.h
 * - ccu_channel_ctx_v1/ccu_channel_ctx_mgr_v1.cc
 *
 * This probe intentionally does not include hcomm/HCCL headers. It is a
 * second implementation of the hcomm packing formulas, used to compare the
 * bytes generated by TileXR's direct-CCU payload packers.
 */

#include "ccu/tilexr_ccu_lower_layer_payloads.h"

#include <algorithm>
#include <array>
#include <cstdint>
#include <cstring>
#include <iostream>

using namespace TileXR;

namespace {

constexpr uint8_t HCOMM_DB_ADDR_TYPE = 1;
constexpr uint8_t HCOMM_TOKEN_VALUE_IS_VALID = 1;
constexpr uint16_t HCOMM_TOKEN_VALUE_VALID = 1;
constexpr uint16_t HCOMM_REMOTE_CCU_VA_RIGHT_SHIFT_NUM = 23;
constexpr uint32_t HCOMM_CCU_WQE_NUM_PER_SQE = 4;

#pragma pack(push, 1)
struct HcommPfeCtx {
    uint16_t startJettyId;
    uint16_t jettyNum : 7;
    uint16_t startLocalJettyCtxId : 7;
    uint16_t rsvBit : 2;
    uint16_t rsv[2];
};

struct HcommLocalJettyCtxData {
    uint16_t doorbellAddr[4];
    uint16_t pfeIdx : 4;
    uint16_t ioDieId : 1;
    uint16_t doorbellAddrType : 1;
    uint16_t tokenValueIsValid : 1;
    uint16_t cqeErrValue : 1;
    uint16_t tokenIdLow : 8;
    uint16_t tokenIdHigh : 12;
    uint16_t tokenValueLow : 4;
    uint16_t tokenValueMiddle;
    uint16_t tokenValueHigh : 12;
    uint16_t sqeBasicBlockLeftShifts : 4;
    uint16_t pi;
    uint16_t ci;
    uint16_t maxCi;
    uint16_t oooCqeCnt : 12;
    uint16_t startWqeBasicBlockIdxLow : 4;
    uint16_t startWqeBasicBlockIdxHigh : 8;
    uint16_t doorbellSendState : 2;
    uint16_t rsvSixBits : 6;
    uint16_t rsvs[3];
};

struct HcommChannelCtxDataV1 {
    uint8_t eidRaw[TILEXR_CCU_EID_BYTES];
    uint16_t vtpLow;
    uint16_t vtpHigh : 8;
    uint16_t srcPfeId : 4;
    uint16_t startJettyIdLow : 4;
    uint16_t startJettyIdHigh : 12;
    uint16_t jettyNumLow : 4;
    uint16_t jettyNumHigh : 3;
    uint16_t ioDieId : 1;
    uint16_t dstTokenIdLow : 12;
    uint16_t dstTokenIdHigh : 8;
    uint16_t dstTokenValueLow : 8;
    uint16_t dstTokenValueMiddle;
    uint16_t dstTokenValueHigh : 8;
    uint16_t dstVaLow : 8;
    uint16_t dstVaMiddle;
    uint16_t dstVaHigh;
    uint16_t dstVaHigher : 1;
    uint16_t dstTokenValueValid : 1;
    uint16_t rsv14Bits : 14;
    uint16_t rsvs[14];
};
#pragma pack(pop)

static_assert(sizeof(HcommPfeCtx) == TILEXR_CCU_PFE_CTX_BYTES, "hcomm PFE ctx size mismatch");
static_assert(sizeof(HcommLocalJettyCtxData) == TILEXR_CCU_LOCAL_JETTY_CTX_BYTES,
    "hcomm local jetty ctx size mismatch");
static_assert(sizeof(HcommChannelCtxDataV1) == TILEXR_CCU_CHANNEL_CTX_V1_BYTES,
    "hcomm channel ctx v1 size mismatch");

uint16_t Log2PowerOfTwo(uint32_t value)
{
    uint16_t log2 = 0;
    while (value > 1U) {
        value >>= 1U;
        ++log2;
    }
    return log2;
}

HcommPfeCtx BuildHcommPfeCtx(
    uint16_t startTaJettyId,
    uint16_t jettyCount,
    uint16_t startLocalJettyCtxId)
{
    HcommPfeCtx ctx {};
    ctx.startJettyId = startTaJettyId;
    ctx.jettyNum = static_cast<uint16_t>(jettyCount - 1U);
    ctx.startLocalJettyCtxId = startLocalJettyCtxId;
    return ctx;
}

HcommLocalJettyCtxData BuildHcommLocalJettyCtx(
    uint8_t dieId,
    uint32_t pfeId,
    uint64_t doorbellVa,
    uint32_t doorbellTokenId,
    uint32_t doorbellTokenValue,
    uint32_t sqDepth,
    uint16_t wqeBasicBlockStartId)
{
    HcommLocalJettyCtxData data {};
    uint16_t doorbell[4] {};
    std::memcpy(doorbell, &doorbellVa, sizeof(doorbell));
    data.doorbellAddr[0] = doorbell[0];
    data.doorbellAddr[1] = doorbell[1];
    data.doorbellAddr[2] = doorbell[2];
    data.doorbellAddr[3] = doorbell[3];
    data.pfeIdx = static_cast<uint8_t>(pfeId);
    data.ioDieId = dieId;
    data.doorbellAddrType = HCOMM_DB_ADDR_TYPE;
    data.tokenValueIsValid = HCOMM_TOKEN_VALUE_IS_VALID;
    data.tokenIdLow = doorbellTokenId & 0x000000ffU;
    data.tokenIdHigh = (doorbellTokenId >> 8U) & 0x00000fffU;
    data.tokenValueLow = doorbellTokenValue & 0x0000000fU;
    data.tokenValueMiddle = (doorbellTokenValue >> 4U) & 0x0000ffffU;
    data.tokenValueHigh = (doorbellTokenValue >> 20U) & 0x00000fffU;
    data.sqeBasicBlockLeftShifts = Log2PowerOfTwo(sqDepth * HCOMM_CCU_WQE_NUM_PER_SQE);
    data.startWqeBasicBlockIdxLow = wqeBasicBlockStartId & 0x0000000fU;
    data.startWqeBasicBlockIdxHigh = (wqeBasicBlockStartId >> 4U) & 0x000000ffU;
    return data;
}

HcommChannelCtxDataV1 BuildHcommChannelCtxV1(
    const std::array<uint8_t, TILEXR_CCU_EID_BYTES>& remoteEid,
    uint32_t tpn,
    uint32_t feId,
    uint16_t startTaJettyId,
    uint16_t jettyCount,
    uint8_t dieId,
    uint32_t memTokenId,
    uint32_t memTokenValue,
    uint64_t remoteCcuVa)
{
    HcommChannelCtxDataV1 data {};
    std::copy(remoteEid.begin(), remoteEid.end(), data.eidRaw);
    data.vtpLow = tpn & 0x0000ffffU;
    data.vtpHigh = ((tpn & 0xffff0000U) >> 16U) & 0x000000ffU;
    data.srcPfeId = static_cast<uint16_t>(feId);
    data.startJettyIdLow = startTaJettyId & 0x000fU;
    data.startJettyIdHigh = (startTaJettyId >> 4U) & 0x0fffU;
    const uint8_t jettyNum = static_cast<uint8_t>(jettyCount - 1U);
    data.jettyNumLow = jettyNum & 0x000fU;
    data.jettyNumHigh = (jettyNum >> 4U) & 0x0007U;
    data.ioDieId = dieId;
    data.dstTokenIdLow = memTokenId & 0x00000fffU;
    data.dstTokenIdHigh = (memTokenId >> 12U) & 0x000000ffU;
    data.dstTokenValueLow = memTokenValue & 0x000000ffU;
    data.dstTokenValueMiddle = (memTokenValue >> 8U) & 0x0000ffffU;
    data.dstTokenValueHigh = (memTokenValue >> 24U) & 0x000000ffU;
    const uint64_t dstVa = remoteCcuVa >> HCOMM_REMOTE_CCU_VA_RIGHT_SHIFT_NUM;
    data.dstVaLow = dstVa & 0x00000000000000ffULL;
    data.dstVaMiddle = (dstVa >> 8U) & 0x000000000000ffffULL;
    data.dstVaHigh = (dstVa >> 24U) & 0x000000000000ffffULL;
    data.dstVaHigher = (dstVa >> 40U) & 0x0000000000000001ULL;
    data.dstTokenValueValid = HCOMM_TOKEN_VALUE_VALID;
    return data;
}

template <typename HcommStruct, typename TileXRStruct>
bool RawEquals(const HcommStruct& expected, const TileXRStruct& actual)
{
    return sizeof(expected) == sizeof(actual.raw) &&
        std::memcmp(&expected, actual.raw, sizeof(expected)) == 0;
}

template <typename HcommStruct, typename TileXRStruct>
int CheckRawEquals(const char* name, const HcommStruct& expected, const TileXRStruct& actual)
{
    if (RawEquals(expected, actual)) {
        return 0;
    }
    const auto* expectedBytes = reinterpret_cast<const uint8_t*>(&expected);
    for (uint32_t i = 0; i < sizeof(expected); ++i) {
        if (expectedBytes[i] != actual.raw[i]) {
            std::cerr << name << " mismatch at byte " << i
                      << " expected=0x" << std::hex << static_cast<uint32_t>(expectedBytes[i])
                      << " actual=0x" << static_cast<uint32_t>(actual.raw[i])
                      << std::dec << "\n";
            return 1;
        }
    }
    std::cerr << name << " mismatch\n";
    return 1;
}

int CheckPfe()
{
    TileXRCcuPfeCtx actual;
    TileXRCcuLowerLayerPayloadReport report;
    TileXRCcuPfeCtxSpec spec;
    spec.startJettyId = 0x1234;
    spec.jettyCount = 5;
    spec.startLocalJettyCtxId = 0x22;
    if (TileXRCcuBuildPfeCtx(spec, &actual, &report) != TILEXR_SUCCESS) {
        std::cerr << "TileXR PFE build failed: " << report.message << "\n";
        return 1;
    }
    return CheckRawEquals("PFE", BuildHcommPfeCtx(0x1234, 5, 0x22), actual);
}

int CheckJetty()
{
    TileXRCcuLocalJettyCtxData actual;
    TileXRCcuLowerLayerPayloadReport report;
    TileXRCcuLocalJettyCtxSpec spec;
    spec.dieId = 1;
    spec.pfeId = 3;
    spec.doorbellVa = 0x1122334455667788ULL;
    spec.doorbellTokenId = 0x000abcdeU;
    spec.doorbellTokenValue = 0x89abcdefU;
    spec.sqDepth = 16;
    spec.wqeBasicBlockStartId = 0x9a;
    if (TileXRCcuBuildLocalJettyCtx(spec, &actual, &report) != TILEXR_SUCCESS) {
        std::cerr << "TileXR jetty build failed: " << report.message << "\n";
        return 1;
    }
    return CheckRawEquals(
        "Jetty",
        BuildHcommLocalJettyCtx(1, 3, 0x1122334455667788ULL, 0x000abcdeU, 0x89abcdefU, 16, 0x9a),
        actual);
}

int CheckChannel()
{
    std::array<uint8_t, TILEXR_CCU_EID_BYTES> remoteEid {};
    for (uint32_t i = 0; i < remoteEid.size(); ++i) {
        remoteEid[i] = static_cast<uint8_t>(0x10 + i);
    }

    TileXRCcuChannelCtxDataV1 actual;
    TileXRCcuLowerLayerPayloadReport report;
    TileXRCcuChannelCtxV1Spec spec;
    spec.remoteEid = remoteEid;
    spec.tpn = 0x00ab5678U;
    spec.sourcePfeId = 5;
    spec.startJettyId = 0x0234;
    spec.jettyCount = 7;
    spec.dieId = 1;
    spec.memoryTokenId = 0x000abcdeU;
    spec.memoryTokenValue = 0x89abcdefU;
    spec.remoteCcuVa = 0x000123456789ab00ULL;
    if (TileXRCcuBuildChannelCtxV1(spec, &actual, &report) != TILEXR_SUCCESS) {
        std::cerr << "TileXR channel build failed: " << report.message << "\n";
        return 1;
    }
    return CheckRawEquals(
        "Channel",
        BuildHcommChannelCtxV1(
            remoteEid,
            0x00ab5678U,
            5,
            0x0234,
            7,
            1,
            0x000abcdeU,
            0x89abcdefU,
            0x000123456789ab00ULL),
        actual);
}

int CheckZeroTokenValues()
{
    TileXRCcuLowerLayerPayloadReport report;
    TileXRCcuLocalJettyCtxData actualJetty;
    TileXRCcuLocalJettyCtxSpec jettySpec;
    jettySpec.dieId = 0;
    jettySpec.pfeId = 2;
    jettySpec.doorbellVa = 0x1020304050607080ULL;
    jettySpec.doorbellTokenId = 0x12345U;
    jettySpec.doorbellTokenValue = 0;
    jettySpec.sqDepth = 8;
    if (TileXRCcuBuildLocalJettyCtx(jettySpec, &actualJetty, &report) != TILEXR_SUCCESS) {
        std::cerr << "TileXR zero-token jetty build failed: " << report.message << "\n";
        return 1;
    }
    if (CheckRawEquals(
            "ZeroTokenJetty",
            BuildHcommLocalJettyCtx(0, 2, 0x1020304050607080ULL, 0x12345U, 0, 8, 0),
            actualJetty) != 0) {
        return 1;
    }

    std::array<uint8_t, TILEXR_CCU_EID_BYTES> remoteEid {};
    for (uint32_t i = 0; i < remoteEid.size(); ++i) {
        remoteEid[i] = static_cast<uint8_t>(0xa0 + i);
    }
    TileXRCcuChannelCtxDataV1 actualChannel;
    TileXRCcuChannelCtxV1Spec channelSpec;
    channelSpec.remoteEid = remoteEid;
    channelSpec.tpn = 0x13579U;
    channelSpec.sourcePfeId = 2;
    channelSpec.startJettyId = 0x44;
    channelSpec.jettyCount = 1;
    channelSpec.dieId = 0;
    channelSpec.memoryTokenId = 0x12345U;
    channelSpec.memoryTokenValue = 0;
    channelSpec.remoteCcuVa = 0x0000001234000000ULL;
    if (TileXRCcuBuildChannelCtxV1(channelSpec, &actualChannel, &report) != TILEXR_SUCCESS) {
        std::cerr << "TileXR zero-token channel build failed: " << report.message << "\n";
        return 1;
    }
    return CheckRawEquals(
        "ZeroTokenChannel",
        BuildHcommChannelCtxV1(remoteEid, 0x13579U, 2, 0x44, 1, 0, 0x12345U, 0, 0x0000001234000000ULL),
        actualChannel);
}

} // namespace

int main()
{
    if (CheckPfe() != 0 || CheckJetty() != 0 || CheckChannel() != 0 || CheckZeroTokenValues() != 0) {
        return 1;
    }
    std::cout << "hcomm lower-layer payload oracle matched" << std::endl;
    return 0;
}
