if(NOT DEFINED TILEXR_EP_COMBINE_MEMORY_OP)
    message(FATAL_ERROR "TILEXR_EP_COMBINE_MEMORY_OP is required")
endif()
if(NOT DEFINED TILEXR_EP_COMBINE_MEMORY_EMBED_CPP)
    message(FATAL_ERROR "TILEXR_EP_COMBINE_MEMORY_EMBED_CPP is required")
endif()
if(NOT EXISTS "${TILEXR_EP_COMBINE_MEMORY_OP}")
    message(FATAL_ERROR "Combine memory CCE object not found: ${TILEXR_EP_COMBINE_MEMORY_OP}")
endif()

file(SIZE "${TILEXR_EP_COMBINE_MEMORY_OP}" _tilexr_ep_combine_memory_size)

file(WRITE "${TILEXR_EP_COMBINE_MEMORY_EMBED_CPP}" "/*
 * Generated by src/ep/cmake/embed_combine_memory_kernel.cmake.
 */
#include <cstddef>
#include <cstdint>

extern \"C\" {
extern const std::size_t TileXREpCombineMemoryKernelBinarySize = ${_tilexr_ep_combine_memory_size};
}

asm(R\"(
.section .rodata, \"a\", @progbits
.balign 16
.global TileXREpCombineMemoryKernelBinaryData
.type TileXREpCombineMemoryKernelBinaryData, @object
TileXREpCombineMemoryKernelBinaryData:
.incbin \"${TILEXR_EP_COMBINE_MEMORY_OP}\"
TileXREpCombineMemoryKernelBinaryDataEnd:
.size TileXREpCombineMemoryKernelBinaryData, TileXREpCombineMemoryKernelBinaryDataEnd - TileXREpCombineMemoryKernelBinaryData
.previous
)\");
")
