if(NOT DEFINED TILEXR_EP_DISPATCH_MEMORY_OP)
    message(FATAL_ERROR "TILEXR_EP_DISPATCH_MEMORY_OP is required")
endif()
if(NOT DEFINED TILEXR_EP_DISPATCH_MEMORY_EMBED_CPP)
    message(FATAL_ERROR "TILEXR_EP_DISPATCH_MEMORY_EMBED_CPP is required")
endif()
if(NOT EXISTS "${TILEXR_EP_DISPATCH_MEMORY_OP}")
    message(FATAL_ERROR "Dispatch memory CCE object not found: ${TILEXR_EP_DISPATCH_MEMORY_OP}")
endif()

file(SIZE "${TILEXR_EP_DISPATCH_MEMORY_OP}" _tilexr_ep_dispatch_memory_size)

file(WRITE "${TILEXR_EP_DISPATCH_MEMORY_EMBED_CPP}" "/*
 * Generated by src/ep/cmake/embed_dispatch_memory_kernel.cmake.
 */
#include <cstddef>
#include <cstdint>

extern \"C\" {
extern const std::size_t TileXREpDispatchMemoryKernelBinarySize = ${_tilexr_ep_dispatch_memory_size};
}

asm(R\"(
.section .rodata, \"a\", @progbits
.balign 16
.global TileXREpDispatchMemoryKernelBinaryData
.type TileXREpDispatchMemoryKernelBinaryData, @object
TileXREpDispatchMemoryKernelBinaryData:
.incbin \"${TILEXR_EP_DISPATCH_MEMORY_OP}\"
TileXREpDispatchMemoryKernelBinaryDataEnd:
.size TileXREpDispatchMemoryKernelBinaryData, TileXREpDispatchMemoryKernelBinaryDataEnd - TileXREpDispatchMemoryKernelBinaryData
.previous
)\");
")
